import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Scale, Clock, MapPin, Building2, Tag } from 'lucide-react';

// This component is rendered off-screen specifically for PDF generation.
export const SummaryExportCard = React.forwardRef(({ doc }, ref) => {
  if (!doc) return null;

  const url = `http://localhost:5173/document/${doc.id}`; // Will be real URL in production

  return (
    <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: 0, overflow: 'hidden', pointerEvents: 'none', zIndex: -100 }}>
      {/* 
        A4 Size mapping: 210mm x 297mm. 
        At 96 DPI, this is roughly 794px x 1123px.
      */}
      <div 
        ref={ref} 
        style={{
          width: '794px',
          minHeight: '1123px',
          backgroundColor: '#0a0f1e', // Dark navy background
          color: '#e2e8f0',
          padding: '40px 50px',
          fontFamily: 'Inter, system-ui, sans-serif',
          boxSizing: 'border-box',
          display: 'flex',
          flexDirection: 'column'
        }}
      >
        {/* Header Section */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid rgba(245, 158, 11, 0.3)', paddingBottom: '20px', marginBottom: '30px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '15px' }}>
              <div style={{ background: 'linear-gradient(135deg,#f59e0b,#fb923c)', padding: '8px', borderRadius: '8px', display: 'flex' }}>
                <Scale size={24} color="#0a0f1e" strokeWidth={2.5} />
              </div>
              <span style={{ fontSize: '1.5rem', fontWeight: 800, color: '#f8fafc', letterSpacing: '-0.02em' }}>
                Kanan Legal Intelligence
              </span>
            </div>
            <h1 style={{ fontSize: '1.8rem', fontWeight: 700, lineHeight: 1.3, color: '#f8fafc', margin: 0, maxWidth: '550px' }}>
              {doc.title}
            </h1>
          </div>
          
          <div style={{ background: '#ffffff', padding: '10px', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '8px' }}>
            <QRCodeSVG value={url} size={90} />
            <span style={{ color: '#0a0f1e', fontSize: '0.65rem', fontWeight: 600 }}>SCAN TO VIEW</span>
          </div>
        </div>

        {/* Metadata Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '15px', marginBottom: '35px', background: 'rgba(30, 41, 59, 0.5)', padding: '20px', borderRadius: '12px' }}>
          <MetaItem icon={<Tag size={16} />} label="DOCUMENT TYPE" value={doc.doc_type?.toUpperCase()} />
          <MetaItem icon={<Clock size={16} />} label="YEAR" value={doc.publish_year} />
          <MetaItem icon={<MapPin size={16} />} label="REGION" value={doc.region === 'gujarat' ? 'Gujarat' : doc.region === 'central' ? 'Central' : doc.region} />
          <MetaItem icon={<Building2 size={16} />} label="DEPARTMENT" value={doc.department || 'N/A'} />
        </div>

        {/* AI Summary Section */}
        <div style={{ flex: 1 }}>
          <h2 style={{ fontSize: '1.2rem', fontWeight: 600, color: '#f59e0b', marginBottom: '15px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            AI Generated Summary
          </h2>
          <div style={{ fontSize: '1.05rem', lineHeight: 1.7, color: '#cbd5e1', whiteSpace: 'pre-wrap' }}>
            {doc.summary_en || "No summary available for this document."}
          </div>
        </div>

        {/* Footer */}
        <div style={{ borderTop: '1px solid rgba(148, 163, 184, 0.2)', paddingTop: '20px', marginTop: '40px', display: 'flex', justifyContent: 'space-between', color: '#64748b', fontSize: '0.85rem' }}>
          <span>Generated by Kanan Platform</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
});

function MetaItem({ icon, label, value }) {
  if (!value) return null;
  return (
    <div style={{ display: 'flex', gap: '10px', alignItems: 'flex-start' }}>
      <span style={{ color: '#94a3b8', marginTop: '2px' }}>{icon}</span>
      <div>
        <div style={{ fontSize: '0.7rem', color: '#94a3b8', fontWeight: 600, letterSpacing: '0.05em' }}>{label}</div>
        <div style={{ fontSize: '0.95rem', color: '#f8fafc', fontWeight: 500 }}>{value}</div>
      </div>
    </div>
  );
}
